networks:
  proxy:
    name: proxy_network
    external: true

services:
  youtrack:
    image: jetbrains/youtrack:2023.1.9689
    volumes:
      - './data:/opt/youtrack/data'
      - './logs:/opt/youtrack/logs'
      - './conf:/opt/youtrack/conf'
      - './backups:/opt/youtrack/backups'
    restart: always
    networks:
      - proxy
    ports:
      - '8081:8080'
